version: '3.4'
services:
  postgres:
    image: 'postgis/postgis:latest'
    restart: always
    volumes:
      - 'gasdata:/var/lib/postgresql/data'
    environment:
      - POSTGRES_PASSWORD=123
    ports:
      - '5432:5432'
  scrapper:
    build:
      context: ./
      dockerfile: Dockerfile
      target: scrapper
    environment:
      - FLASK_ENV=development
    depends_on:
      - postgres
  app:
    build:
      context: ./
      dockerfile: Dockerfile
      target: app
    restart: always
    environment:
      - FLASK_ENV=development
    depends_on:
      - postgres
    ports:
      - '5000:5000'
volumes:
  gasdata: